name: CI for Renovate

on:
  pull_request:
    paths:
      - .github/workflows/ci-renovate.yaml
      - renovate.json5

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint:renovate-config-validator
