name: ci

on: [pull_request]

jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    env:
      ARTICLES_PATH: articles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: corepack enable npm
      - run: npm ci
      - name: textlint / github-check
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          reporter: github-check
          textlint_flags: "${{ env.ARTICLES_PATH }}/**/**"

  actionlint:
    name: actionlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: corepack enable npm
      - run: npm ci
      - name: actionlint
        run: npm run lint:node-actionlint

  validate-renovate-config:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: corepack enable npm
      - run: npm ci
      - run: npm run lint:renovate-config-validator

  validate-zenn-metadata:
    name: Validate Zenn metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Because if `fetch-depth >= 2` is not set, unchanged files will be updated.
      - uses: korosuke613/zenn-metadata-updater-action@feat-validate-metadata
        with:
          validate-only: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
