name: "PR Analytics"
on:
  workflow_dispatch:
  schedule:
    - cron: '3 10 1 * *'

permissions:
  issues: write

jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: 1 ヶ月前の範囲を取得 # 例: 7 月に実行した場合、2023-06-01..2023-06-30 のようになる
        shell: bash
        id: days
        run: |
          # Calculate the first day of the previous month
          echo "issue_title=Pull requests report($(date -d "last month" +%Y/%m))" >> "$GITHUB_OUTPUT"

      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@01d9a216d16b2eee2ce048c748f3acaac8882990 # v4.8.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNERS_REPOS: ${{ github.repository }}
          GITHUB_REPO_FOR_ISSUE: ${{ github.event.repository.name }}
          GITHUB_OWNER_FOR_ISSUE: ${{ github.repository_owner }}
          CORE_HOURS_START: "10:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Asia/Tokyo"
          REPORT_PERIOD: "months:3"
          AGGREGATE_VALUE_METHODS: average
          PERIOD_SPLIT_UNIT: none
          TOP_LIST_AMOUNT: 5
          HIDE_USERS: "github-actions[bot],renovate[bot]"
          EXECUTION_OUTCOME: "existing-issue"
          ISSUE_NUMBER: ${{ vars.ISSUE_NUMBER }}
          ISSUE_TITLE: ${{ steps.days.outputs.issue_title }}
